apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ko2-demo-acc
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: ko2-demo-acc
spec:
  env:
  - name: APP_MESSAGE
    value: KO2 Team
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/serpiko2/ko2-demo-acc
      ref:
        branch: main
